name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.x'
    - name: Run tests
      run: go test -cover ./...
    - name: Run tests for cmd/spline
      working-directory: cmd/spline
      run: go test -cover ./...
